services:
  dmkbot:
    image: ${IMAGE_NAME:-recod0/dmkbot}:${TAG:-latest}
    container_name: dmkbot
    restart: unless-stopped
    environment:
      TG_TOKEN: ${TG_TOKEN}
      API_KEY: ${API_KEY}
      WIALON_TOKEN: ${WIALON_TOKEN}
    ports:
      - "8010:8000"
    volumes:
      - /var/opt/dmkbot/db:/olymp/db
