services:
  dmk-logistic:
    image: ${DOCKER_IMAGE:-recod0/dmk-logistic:latest}
    container_name: dmk-logistic
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./data:/olymp/db
