services:
  app:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    volumes:
      - /var/opt/dmkbot/db:/olymp/db
    ports:
      - "8010:8000"
    environment:
      TG_TOKEN: ${TG_TOKEN}
      API_KEY: ${API_KEY}
      WIALON_TOKEN: ${WIALON_TOKEN}
